### ISSUE TITLE
Crash upon selecting in NPP 8.3

### ISSUE THREAD

**Issue by benpratt** [KubaDee/SelectToClipboard#1]
I just updated my Notepad++ from v8.2.1 to v8.3 and as soon as I select text with the Select to Clipboard plugin installed NPP crashes.

There were two other plugins, Compare and DSpellCheck, that prompted me for an update as soon as I launched v8.3. I don't know that it's related but just something I noted.

**Comment by jnpapado** [comment]
Same issue with v8.3.3. N++ crashes if plugin is activated and a selection is made.

**Comment by vinsworldcom** [comment]
@KubaDee All plugins making use of `Sci_PositionCR` need to be recompiled to support Notepad++ > 8.3.

https://community.notepad-plus-plus.org/topic/22471/recompile-your-x64-plugins-with-new-header

Cheers.

**Comment by rdipardo** [comment]
Here is a patched 64-bit build to try; you'll need to extract it to `<NPP_INSTALL_DIR>\plugins\SelectToClipboard`:  

- [SelectToClipboard_x64_v1.0.2.1-c20ac14.zip](https://github.com/KubaDee/SelectToClipboard/files/8445627/SelectToClipboard_x64_v1.0.2.1-c20ac14.zip)
- [sha256sum.txt](https://github.com/KubaDee/SelectToClipboard/files/8445648/sha256sum.txt)

In case @KubaDee is still maintaining this, here's a patch for the outdated plugin interface files:
[0001-Update-plugin-interface.patch.txt](https://github.com/KubaDee/SelectToClipboard/files/8445639/0001-Update-plugin-interface.patch.txt)

**Comment by KubaDee** [comment]
Hi, thanks for pointing it out. Was busy last weeks. Hope that will get time next week to update ir according latest changes on NPP.

**Comment by KubaDee** [comment]
@vinsworldcom @jnpapado 
Fixed in new version 1.0.3
